version: '3.3'

services:
  app:
    image: python:3.11.2
    build:
      context: .
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - 8000:8000
    command: bash -c "cd app
                      && pip install poetry
                      && poetry install
                      && make automigrate
                      && make migrate
                      && make run-server"


  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./pgdata:/var/lib/postgres/data
    ports:
      - ${DB_PORT}:5432
